import type { Repo, ScanResult, ScanHistoryEntry } from '@/types'

export const MOCK_REPOS: Repo[] = [
  {
    id: 'repo-1',
    githubId: 100001,
    name: 'api-gateway',
    full_name: 'demo/api-gateway',
    owner: 'demo',
    description: 'Core API gateway service with rate limiting and auth middleware',
    language: 'TypeScript',
    languageColor: '#F7DF1E',
    visibility: 'private',
    updatedAt: '2h ago',
    defaultBranch: 'main',
    fileCount: 98,
    lastScan: { id: 'scan-1', completedAt: '1d ago', findingCount: 3 },
  },
  {
    id: 'repo-2',
    githubId: 100002,
    name: 'data-pipeline',
    full_name: 'demo/data-pipeline',
    owner: 'demo',
    description: 'ETL pipeline for processing and transforming customer analytics data',
    language: 'Python',
    languageColor: '#3572A5',
    visibility: 'private',
    updatedAt: '5h ago',
    defaultBranch: 'main',
    fileCount: 142,
  },
  {
    id: 'repo-3',
    githubId: 100003,
    name: 'auth-service',
    full_name: 'demo/auth-service',
    owner: 'demo',
    description: 'OAuth2 authentication service with JWT token management',
    language: 'Go',
    languageColor: '#00ADD8',
    visibility: 'public',
    updatedAt: '1d ago',
    defaultBranch: 'main',
    fileCount: 64,
  },
  {
    id: 'repo-4',
    githubId: 100004,
    name: 'frontend-app',
    full_name: 'demo/frontend-app',
    owner: 'demo',
    description: 'Next.js customer-facing application with dashboard and analytics',
    language: 'TypeScript',
    languageColor: '#F7DF1E',
    visibility: 'public',
    updatedAt: '3d ago',
    defaultBranch: 'main',
    fileCount: 211,
  },
  {
    id: 'repo-5',
    githubId: 100005,
    name: 'infra',
    full_name: 'demo/infra',
    owner: 'demo',
    description: 'Terraform and Helm charts for Kubernetes cluster provisioning',
    language: 'HCL',
    languageColor: '#844FBA',
    visibility: 'private',
    updatedAt: '6d ago',
    defaultBranch: 'main',
    fileCount: 47,
  },
  {
    id: 'repo-6',
    githubId: 100006,
    name: 'ml-models',
    full_name: 'demo/ml-models',
    owner: 'demo',
    description: 'Training pipelines and model serving infrastructure',
    language: 'Python',
    languageColor: '#3572A5',
    visibility: 'private',
    updatedAt: '2d ago',
    defaultBranch: 'main',
    fileCount: 183,
  },
]

export const MOCK_SCAN_RESULT: ScanResult = {
  id: 'scan-demo-1',
  repoId: 'repo-2',
  repoName: 'data-pipeline',
  status: 'complete',
  branch: 'main',
  commitSha: 'a3f92c1',
  startedAt: new Date(Date.now() - 154000).toISOString(),
  completedAt: new Date().toISOString(),
  durationMs: 154000,
  fileCount: 142,
  findings: [
    {
      id: 'f-1',
      tool: 'gitleaks',
      severity: 'critical',
      title: 'Hardcoded AWS credentials detected',
      description:
        'AWS access key and secret found in plaintext. These credentials provide access to production S3 buckets and should be rotated immediately and moved to environment variables or a secrets manager.',
      file: 'src/connectors/s3_client.py',
      line: 34,
      rule: 'aws-access-token',
      snippet: 'AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"',
    },
    {
      id: 'f-2',
      tool: 'gitleaks',
      severity: 'critical',
      title: 'SQL injection vulnerability',
      description:
        'User-controlled input is directly interpolated into a SQL query without sanitisation or parameterised queries. An attacker could manipulate the query to extract or destroy data.',
      file: 'src/db/query_builder.py',
      line: 112,
      rule: 'python.lang.security.audit.sqli',
      snippet: 'cursor.execute(f"SELECT * FROM users WHERE id = {user_id}")',
    },
    {
      id: 'f-3',
      tool: 'trivy',
      severity: 'high',
      title: 'Insecure deserialization with pickle',
      description:
        'Deserializing untrusted data using pickle can lead to arbitrary code execution. Consider using a safer serialisation format like JSON.',
      file: 'src/cache/model_cache.py',
      line: 67,
      rule: 'python.lang.security.insecure-deserialization',
      snippet: 'model = pickle.loads(cached_data)',
    },
    {
      id: 'f-4',
      tool: 'trivy',
      severity: 'high',
      title: 'High entropy string — possible secret',
      description:
        'A high-entropy string was detected that may be a private key, token, or password. Flagged for manual review.',
      file: 'config/production.env.example',
      line: 8,
      rule: 'high-entropy-string',
    },
    {
      id: 'f-5',
      tool: 'gitleaks',
      severity: 'high',
      title: 'Command injection via subprocess',
      description:
        'shell=True with user-controlled input allows arbitrary shell command execution. Use a list of arguments instead.',
      file: 'src/utils/shell_runner.py',
      line: 23,
      rule: 'python.lang.security.audit.subprocess-shell-true',
      snippet: 'subprocess.run(f"convert {filename}", shell=True)',
    },
    {
      id: 'f-6',
      tool: 'trivy',
      severity: 'medium',
      title: 'Logging sensitive user data',
      description:
        'A log statement appears to include raw request parameters that may contain PII or credentials.',
      file: 'src/middleware/logging.py',
      line: 55,
      rule: 'python.lang.security.audit.logging-pii',
    },
    {
      id: 'f-7',
      tool: 'trivy',
      severity: 'low',
      title: 'Use of outdated MD5 hash function',
      description:
        'MD5 is cryptographically broken and unsuitable for security purposes. Migrate to SHA-256 or bcrypt depending on the use case.',
      file: 'src/auth/token_gen.py',
      line: 18,
      rule: 'python.lang.security.audit.use-defusedxml',
    },
  ],
}

export const MOCK_SCAN_HISTORY: ScanHistoryEntry[] = [
  { id: 'scan-1', repoId: 'repo-2', repoName: 'data-pipeline', branch: 'main', status: 'complete', startedAt: new Date(Date.now() - 86400000).toISOString(), completedAt: new Date(Date.now() - 86384600).toISOString(), durationMs: 154000, findingCount: 7 },
  { id: 'scan-2', repoId: 'repo-1', repoName: 'api-gateway', branch: 'main', status: 'complete', startedAt: new Date(Date.now() - 172800000).toISOString(), completedAt: new Date(Date.now() - 172778000).toISOString(), durationMs: 22000, findingCount: 3 },
  { id: 'scan-3', repoId: 'repo-4', repoName: 'frontend-app', branch: 'main', status: 'complete', startedAt: new Date(Date.now() - 259200000).toISOString(), completedAt: new Date(Date.now() - 259178000).toISOString(), durationMs: 42000, findingCount: 2 },
  { id: 'scan-4', repoId: 'repo-3', repoName: 'auth-service', branch: 'main', status: 'complete', startedAt: new Date(Date.now() - 345600000).toISOString(), completedAt: new Date(Date.now() - 345578000).toISOString(), durationMs: 18000, findingCount: 0 },
]
